services:
  alfgow-nvr:
    build: .
    container_name: alfgow-nvr
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /mnt/storage-alfgow/alfgow-nvr
        target: /mnt/storage-alfgow/alfgow-nvr
        bind:
          propagation: rshared

  ffmpeg-cam1:
    image: linuxserver/ffmpeg:latest
    container_name: ffmpeg-cam1
    restart: unless-stopped
    command: >
      -rtsp_transport tcp
      -fflags nobuffer
      -i rtsp://admin:D210512d@192.168.0.122:554/Streaming/Channels/101
      -an
      -c:v libx264
      -preset ultrafast
      -tune zerolatency
      -profile:v baseline
      -level 3.1
      -pix_fmt yuv420p
      -b:v 1800k
      -maxrate 2200k
      -bufsize 1800k
      -g 12
      -keyint_min 12
      -sc_threshold 0
      -bf 0
      -force_key_frames 'expr:gte(t,n_forced*0.5)'
      -f hls
      -hls_time 0.5
      -hls_list_size 2
      -hls_delete_threshold 1
      -hls_flags delete_segments+independent_segments+omit_endlist
      /mnt/storage-alfgow/alfgow-nvr/live/cam1/index.m3u8
    volumes:
      - type: bind
        source: /mnt/storage-alfgow/alfgow-nvr
        target: /mnt/storage-alfgow/alfgow-nvr
        bind:
          propagation: rshared

  ffmpeg-cam2:
    image: linuxserver/ffmpeg:latest
    container_name: ffmpeg-cam2
    restart: unless-stopped
    command: >
      -rtsp_transport tcp
      -fflags nobuffer
      -i rtsp://admin:D210512d@192.168.0.122:554/Streaming/Channels/201
      -an
      -c:v libx264
      -preset ultrafast
      -tune zerolatency
      -profile:v baseline
      -level 3.1
      -pix_fmt yuv420p
      -b:v 1800k
      -maxrate 2200k
      -bufsize 1800k
      -g 12
      -keyint_min 12
      -sc_threshold 0
      -bf 0
      -force_key_frames 'expr:gte(t,n_forced*0.5)'
      -f hls
      -hls_time 0.5
      -hls_list_size 2
      -hls_delete_threshold 1
      -hls_flags delete_segments+independent_segments+omit_endlist
      /mnt/storage-alfgow/alfgow-nvr/live/cam2/index.m3u8
    volumes:
      - type: bind
        source: /mnt/storage-alfgow/alfgow-nvr
        target: /mnt/storage-alfgow/alfgow-nvr
        bind:
          propagation: rshared

  ffmpeg-cam3:
    image: linuxserver/ffmpeg:latest
    container_name: ffmpeg-cam3
    restart: unless-stopped
    command: >
      -rtsp_transport tcp
      -fflags nobuffer
      -i rtsp://admin:D210512d@192.168.0.122:554/Streaming/Channels/301
      -an
      -c:v libx264
      -preset ultrafast
      -tune zerolatency
      -profile:v baseline
      -level 3.1
      -pix_fmt yuv420p
      -b:v 1800k
      -maxrate 2200k
      -bufsize 1800k
      -g 12
      -keyint_min 12
      -sc_threshold 0
      -bf 0
      -force_key_frames 'expr:gte(t,n_forced*0.5)'
      -f hls
      -hls_time 0.5
      -hls_list_size 2
      -hls_delete_threshold 1
      -hls_flags delete_segments+independent_segments+omit_endlist
      /mnt/storage-alfgow/alfgow-nvr/live/cam3/index.m3u8
    volumes:
      - type: bind
        source: /mnt/storage-alfgow/alfgow-nvr
        target: /mnt/storage-alfgow/alfgow-nvr
        bind:
          propagation: rshared

  ffmpeg-cam4:
    image: linuxserver/ffmpeg:latest
    container_name: ffmpeg-cam4
    restart: unless-stopped
    command: >
      -rtsp_transport tcp
      -fflags nobuffer
      -i rtsp://admin:D210512d@192.168.0.122:554/Streaming/Channels/401
      -an
      -c:v libx264
      -preset ultrafast
      -tune zerolatency
      -profile:v baseline
      -level 3.1
      -pix_fmt yuv420p
      -b:v 1800k
      -maxrate 2200k
      -bufsize 1800k
      -g 12
      -keyint_min 12
      -sc_threshold 0
      -bf 0
      -force_key_frames 'expr:gte(t,n_forced*0.5)'
      -f hls
      -hls_time 0.5
      -hls_list_size 2
      -hls_delete_threshold 1
      -hls_flags delete_segments+independent_segments+omit_endlist
      /mnt/storage-alfgow/alfgow-nvr/live/cam4/index.m3u8
    volumes:
      - type: bind
        source: /mnt/storage-alfgow/alfgow-nvr
        target: /mnt/storage-alfgow/alfgow-nvr
        bind:
          propagation: rshared
